services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=t_students
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend:
    image: localhost:5000/backend-app:latest
    container_name: backend-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/t_students
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    image: localhost:5000/frontend-app:latest
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  db-data:
    name: db-data
    driver: local
networks:
  mon-reseau:
    name: mon-reseau
    external: true
